
;----------------------------------------
; Mount - Defines a single mounted path.
;----------------------------------------
;[mount]

; Exported Path - The path that is exported to clients.
;path = /

; Local Path - The local path where these files for this mount actually are.
;local = /usr/share/tnfsj/public

; Only allow read operations on this mount, regardless of the writability of the underlying file system.
;read-only = false

; A user that can read from this mount. If no read users are defined, \
; then the global `allow-read` in the `mounts` section is used (if any). 
; If `*` is used then *all* users can read this mount anonymously. Use `?` \
; for any authenticated user, or `!` expands to any authenticated user \
; with encryption.
; allow-read = *
	
; A user that can write to this mount. If no write users are defined, \
; then the global `write-user` in the `mounts` section is used (if any).
; If '@' is used then *no* users can write to this mount. If `*` is used then \ 
; any user can write this mount anonymously. Use `?` for any authenticated user, \
; or `!` for any authenticated user with encryption.
; allow-write = *
	
; A user that cannot read from this mount. Any user here will override \
; any `allow-read`  rule that might have allowed it. Only real user names are \
; used here. Any users here are added to those in the global `mounts` section.
; deny-read = 
	
; A user that cannot write to this mount. Any user here will override \
; any `allow-write`  rule that might have allowed it. Only real user names are \
; used here. Any users here are added to those in the global `mounts` section.
; deny-write = 

