secure=Secure
secure.tooltip=Whether to enabled TNFSJ security extension to encrypt all traffic.
basic=Basic
advanced=Advanced
name=Name
hostname=Hostname
port=Port
path=Path
protocol=Protocol
back=Back