mount=Mount
unmount=Unmount
remove=Remove
open=Open ..
edit=Edit

confirmRemove.title=Confirm Remove Mount
confirmRemove.content=Are you sure you wish to remove the mount {0}?
confirmRemove.header=Remove Mount